"use strict";

/**************************************************
 *********** Model or collection Manager **********
 **************************************************/
module.exports = {
  userModel: require("./userModel"),
  appVersionModel: require("./appVersionModel"),
  scheduleModel: require("./scheduleModel"),
  organisationModel: require("./organisationModel"),
  collectorModel: require("./collectorModel"),
  transactionModel: require("./transactionModel"),
  reportModel: require("./reportModel"),
  reportLogModel: require("./reportModelLog"),
  payModel: require("./payModel"),
  companyReceiptModel: require("./companyReceipt"),
  paymentLogModel: require("./paymentLogModel"),
  advertModel: require("./advertModel"),
  payOutModel: require("./payOutModel"),
  versionModel: require("./versionModel"),
  geofenceModel: require("./geofenceModel"),
  dropOffModel: require("./dropOffModel"),
  charityModel: require("./charityModel"),
  scheduleDropModel: require("./scheduleDropModel"),
  notificationModel: require("./notificationModel"),
  localGovernmentModel: require("./localGovernmentModel"),
  categoryModel: require("./categoryModel"),
  locationModel: require("./locationModel"),
  claimsModel: require("./claimsModel"),
  roleModel: require("./roleModel"),
  userBinModel: require("./userbinModel"),
  activitesModel: require("./activitiesModel"),
  worldlocationModel: require("./worldLocationModel"),
  incidentModel: require("./incidentModel"),
  organisationTypeModel: require("./organisationTypeModel"),
  organisationBinModel: require("./organisationBin"),
  collectorBinModel: require("./collectorBin"),
  verificationLogModel: require("./verificationLogModel"),
  resourcesModel: require("./resourcesModel"),
  recentVerificationModel: require("./recentVerificationModel"),
  charityOrganisationModel: require("./charityOrganisationModel"),
  tokenModel: require("./tokenModel"),
};
